---
title: "104-obesus-pop-gen"
output: html_document
date: "2024-04-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
```

The Fish Lake Valley fish appear to be the most divergent 'obesus' (not considering snyderi,toikona subspp.).   

```{r}
library(tidyverse)
library(ggrepel)
library(ggpubr)
```

Meta

Downsampled Paths are at 2e6.   

```{r}
mo5<-read_csv("meta/obesus-500k-meta.csv") %>% mutate(Path2=ifelse(Dedup > 2e6, paste0("data/downsample/",Ind,".reduced.bam"),
                     Path)) %>% mutate(Taxon=Species) %>% filter(Species=="obesus")

obs5<-read_csv("meta/obesus-500k-meta.csv") %>% mutate(Path2=ifelse(Dedup > 2e6, paste0("data/downsample/",Ind,".reduced.bam"),
                     Path)) %>% mutate(Taxon=Species) %>% filter(Species %in% c("obesus","snyderi","toikona"))
mo5 %>% group_by(Species, Vicinity) %>% summarize(Count=n())
```
337 inds without snyderi/toikona
381 inds   
474 inds with snyderi

```{r}
mo5 %>% select(Path) %>% write_csv("bamlists/mo5.bamlist", col_names = FALSE)
mo5 %>% select(Path2) %>% write_csv("bamlists/mo5-downsample.bamlist", col_names = FALSE)

obs5 %>% select(Path) %>% write_csv("bamlists/obs5.bamlist", col_names = FALSE)
obs5 %>% select(Path2) %>% write_csv("bamlists/obs5-downsample.bamlist", col_names = FALSE)
```

at 90% thresh 
```{sh, eval=FALSE}
srun -p bigmemh -t 36:00:00 --mem=128G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12  $HOME/angsd/angsd -P 12  \
-bam bamlists/mo5.bamlist -ref /home/maccamp/genomes/gila-orcutti/GCA_026230005.1_fGilOrc1.0.hap1_genomic.fna.gz \
-minInd 303 -minMapQ 10 -minQ 20 -GL 2 -doGLF 2 \
-doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doIBS 1 -doCounts 1 -doCov 1 -makeMatrix 1 -minMaf 0.01 \
-out outputs/104/mo5-ibs-90 >outputs/104/mo5-ibs-90.out 2> outputs/104/mo5-ibs-90.err &

srun -p bigmemh -t 36:00:00 --mem=128G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12  $HOME/angsd/angsd -P 12  \
-bam bamlists/mo5-downsample.bamlist -ref /home/maccamp/genomes/gila-orcutti/GCA_026230005.1_fGilOrc1.0.hap1_genomic.fna.gz \
-minInd 303 -minMapQ 10 -minQ 20 -GL 2 -doGLF 2 \
-doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doIBS 1 -doCounts 1 -doCov 1 -makeMatrix 1 -minMaf 0.01 \
-out outputs/104/mo5-ibs-90-down >outputs/104/mo5-ibs-90-down.out 2> outputs/104/mo5-ibs-90-down.err &

srun -p high -t 10:00:00 --mem=64G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12  $HOME/angsd/angsd -P 12  \
-bam bamlists/mo5-downsample.bamlist -ref /home/maccamp/genomes/gila-orcutti/GCA_026230005.1_fGilOrc1.0.hap1_genomic.fna.gz \
-minInd 303 -minMapQ 10 -minQ 20 -GL 2 -doGLF 2 \
-doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doIBS 1 -doCounts 1 -doCov 1 -makeMatrix 1 -minMaf 0.01 \
-out outputs/104/mo5-ibs-90-high >outputs/104/mo5-ibs-90-high.out 2> outputs/104/mo5-ibs-90-high.err &

srun -p high -t 04:00:00 --mem=32G --nodes=1 $HOME/angsd/misc/NGSadmix -P 12 -likes outputs/104/mo5-ibs-90-high.beagle.gz -K 2 -minMaf 0.01 -o outputs/104/mo5-K2 &
srun -p high -t 05:00:00 --mem=32G --nodes=1 $HOME/angsd/misc/NGSadmix -P 12 -likes outputs/104/mo5-ibs-90-high.beagle.gz -K 3 -minMaf 0.01 -o outputs/104/mo5-K3 &
srun -p high -t 06:00:00 --mem=32G --nodes=1 $HOME/angsd/misc/NGSadmix -P 12 -likes outputs/104/mo5-ibs-90-high.beagle.gz -K 4 -minMaf 0.01 -o outputs/104/mo5-K4 &
srun -p high -t 06:00:00 --mem=32G --nodes=1 $HOME/angsd/misc/NGSadmix -P 12 -likes outputs/104/mo5-ibs-90-high.beagle.gz -K 5 -minMaf 0.01 -o outputs/104/mo5-K5 &
srun -p high -t 06:00:00 --mem=32G --nodes=1 $HOME/angsd/misc/NGSadmix -P 12 -likes outputs/104/mo5-ibs-90-high.beagle.gz -K 6 -minMaf 0.01 -o outputs/104/mo5-K6 &

```

at maf of 0.01, 184142 sites
minMaf 0.05 90693 sites/336 inds
99948/381 inds at 0.05

```{sh, eval=FALSE}
srun -p high -t 10:00:00 --mem=64G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12  $HOME/angsd/angsd -P 12  \
-bam bamlists/mo5-downsample.bamlist -ref /home/maccamp/genomes/gila-orcutti/GCA_026230005.1_fGilOrc1.0.hap1_genomic.fna.gz \
-minInd 426 -minMapQ 10 -minQ 20 -GL 2 -doGLF 2 \
-doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doIBS 1 -doCounts 1 -doCov 1 -makeMatrix 1 -minMaf 0.01 \
-out outputs/104/obs5-ibs-90-high >outputs/104/obs5-ibs-90-high.out 2> outputs/104/obs5-ibs-90-high.err &

```

```{r}
m <- as.matrix(read.table("outputs/104/mo5-ibs-90-high.covMat"))
eig <- eigen(m)
var<-eig$values/sum(eig$values)
cumvar<-cumsum(eig$values)/sum(eig$values)

head(var)
head(cumvar)

vardf<-as_data_frame(var) %>% mutate(x=1:n())
vardf$cumvar<-cumvar

```

```{r}
eigs<-ggplot(vardf %>% filter(x < 11)) +
  geom_col(aes(x=x, y=value))  +
  scale_x_continuous(breaks=c(1,5,10)) +
  xlab("\nPrincipal Component") +
  ylab("Eigenvalues\n") +
  theme_bw() +
  theme(axis.title = element_text(size=14, face="bold")) +
  theme(panel.grid=element_blank()) +
  theme(axis.text = element_text(size=12))

eigs
```


```{r}
covs<-eig$vectors[,1:3] %>% as_tibble() %>% bind_cols(mo5)

labels12<- covs %>% select(V1, V2, Vicinity) %>% group_by(Vicinity) %>% summarize(x=mean(V1), y=mean(V2))

#labels12<-labels12 %>% filter(Vicinity=="Fish Lake Valley")


pc12<-ggplot(covs) +
  geom_point(aes(x=V1, y=V2, fill=Vicinity), pch=21, cex=3, alpha=0.75) +
  geom_text_repel(data=labels12, aes(x=x, y=y, label=Vicinity), max.overlaps = Inf) +
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = "")) +
  ylab(paste("PC2", " ", round((100*var[2]),2), "%", sep = "")) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  #scale_fill_viridis_c() +
  scale_fill_viridis_d(option="turbo") +
  ggtitle("Genome-Wide PCA of obesus lineages") +
  theme(plot.title = element_text(hjust=0.5, face="bold")) 

pc12
```


```{r}
covs<-eig$vectors[,1:3] %>% as_tibble() %>% bind_cols(mo5)


ggplot(covs) +
  geom_point(aes(x=V1, y=V3, fill=Vicinity), pch=21, cex=3, alpha=0.75) +
  #geom_text_repel(data=text12, aes(x=x, y=y, label=Region), max.overlaps = Inf) +
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = "")) +
  ylab(paste("PC3", " ", round((100*var[3]),2), "%", sep = "")) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  #scale_fill_viridis_c() +
  scale_fill_viridis_d(option="turbo") +
  ggtitle("Genome-Wide PCA of obesus lineages") +
  theme(plot.title = element_text(hjust=0.5, face="bold")) 
```


```{r}
ggarrange(pc12, eigs, widths=c(3,1))
ggsave("outputs/105/obesus-lineages-pca.pdf", width=12, height=5)
```