---
title: "200-sample-map"
output: html_document
date: "2024-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(raster)
library(ggspatial)
library(maps)
library(ggpubr)
library(gridExtra)
library(grid)
library(ggrepel)
library(viridis)
library(polyggon)
```


```{r}
coords<-read_csv("meta/tui-chub-georeferenced-edited.csv")

fish<-read_csv("meta/meta-438-edited.csv")
```

```{r}
ggplot() +
  geom_point(data=coords, aes(x=Longitude, y=Latitude)) +
  coord_equal(1.3)
```
```{r}
samples<-fish %>% group_by(`Tributary/Collection Location`, Genus,Species,Subspecies) %>% summarize(Count=n()) %>% left_join(coords, by=c(`Tributary/Collection Location`="Name"))

samples %>% write_csv("outputs/200/samples.csv")
sum(samples$Count)
```

```{r}
samples<-read_csv("outputs/200/samples-edited.csv")
samples$Taxon<-factor(samples$Species, levels = c("P. macrolepidotus","G. orcuttii","alvordensis","thalassinus","bicolor","newarkensis","isolatus","snyderi","mohavensis","obesus"))
samples$`Sample Size`<-samples$Count
ggplot() +
  geom_point(data=samples, aes(x=Longitude, y=Latitude, fill=Taxon, shape=Taxon)) +
  geom_text_repel(data=samples %>% filter(Taxon=="obesus"), aes(x=Longitude, y=Latitude, label=`Tributary/Collection Location`))+
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  scale_shape_manual(values=c(22,22,23,25,25,24,24,21,21,21)) +
  coord_equal(1.3)
```

How about Great Basin polys?

```{r}
load("spatial-data/cadf.rda")
load("spatial-data/codf.rda")
load("spatial-data/sbgdf.rda")
load("spatial-data/sordf.rda")

```

```{r}
ggplot() +
  geom_polygon(data=cadf, aes(x=long, y=lat, group=group), fill="white", color="black", alpha=0) +
  geom_polygon(data=codf, aes(x=long, y=lat, group=group), fill="white", color="black", alpha=0) +
  geom_polygon(data=sgbdf, aes(x=long, y=lat, group=group), fill="white", color="black", alpha=0) +
  geom_polygon(data=sordf, aes(x=long, y=lat, group=group), fill="white", color="black", alpha=0) +
  geom_point(data=samples, aes(x=Longitude, y=Latitude, fill=Taxon, shape=Taxon)) +
  geom_text_repel(data=samples %>% filter(Taxon=="obesus"), aes(x=Longitude, y=Latitude, label=`Tributary/Collection Location`), max.overlaps = Inf)+
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  scale_shape_manual(values=c(22,22,23,25,25,24,24,21,21,21)) +
  coord_equal(1.3) +
  theme(panel.background = element_blank()) +
  theme(panel.grid=element_blank())
ggsave("outputs/200/samples-with-basins.pdf", width=18, height=12)
```
# States
```{r}
states<-map_data("state") %>% filter(region %in% c("california","oregon","nevada"))

cali<- map_data("state") %>% filter(region %in% c("california"))
domain <- c(min(states$long), max(states$long), min(states$lat), max(states$lat))

# here eric implements something and I copy it
tidy_subset <- function(x, longlat) {
  x@data$id <- rownames(x@data)
  x.f <- broom::tidy(x) %>%
    dplyr::left_join(., x@data, by = "id") %>%
    dplyr::tbl_df() %>%
    filter(long > longlat[1],
           long < longlat[2],
           lat > longlat[3],
           lat < longlat[4])
}

```


```{r, eval=FALSE}
nat.earth<-stack("data/earth/NE2_HR_LC_SR_W_DR/NE2_HR_LC_SR_W_DR.tif")

nat.crop <- crop(nat.earth, y=extent(domain))

rast.table <- data.frame(xyFromCell(nat.crop, 1:ncell(nat.crop)),
                         getValues(nat.crop/255))


rast.table$rgb <- with(rast.table, rgb(NE2_HR_LC_SR_W_DR_1,
                                       NE2_HR_LC_SR_W_DR_2,
                                       NE2_HR_LC_SR_W_DR_3,
                                       1))

save(rast.table, file="data/earth/rast.rda")
```

```{r}
load("data/earth/rast.rda")
ggplot() +
  geom_raster(data = rast.table, mapping = aes(x = x, y = y), fill = rast.table$rgb, interpolate = TRUE)  +
  geom_point(data=samples, aes(x=Longitude, y=Latitude, fill=Taxon, shape=Taxon, size=`Sample Size`)) +
  geom_label_repel(data=samples %>% filter(Taxon=="obesus"), aes(x=Longitude, y=Latitude, label=`Tributary/Collection Location`))+
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  scale_shape_manual(values=c(22,22,23,25,25,24,24,21,21,21)) +
  coord_fixed(ratio=1.3, xlim = c(min(states$long+1), max(cali$long-.5)), ylim=c(min(cali$lat+1), max(cali$lat)+1)) +
  ylab("Latitude\n") +
  xlab("\nLongitude") +
  theme_bw() +
  theme(axis.title = element_text(size=18)) +
  theme(panel.grid=element_blank()) +
  annotation_scale(location = "bl", width_hint = 0.5) + 
  coord_sf(crs = 4326)
ggsave("outputs/200/sampling-map.pdf", width=10, height=8)

```

```{r}
samples %>% filter(Genus %in% c("Epizon","Siphateles")) %>% summarize(Total=sum(Count))
```


## Pleistocene map
Reheis, Marith, 1999, Extent of Pleistocene Lakes in the Western Great Basin: USGS Miscellaneous Field Studies Map MF-2323, U.S. Geological Survey, Denver, CO
http://pubs.usgs.gov/mf/1999/mf-2323/



