---
title: "206-species-tree"
output: html_document
date: "2025-06-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(ggrepel)
library(poppr)
library(vcfR)
library(phytools)
library(phangorn)
library(ape)
library(ggtree)
library(tanggle)
```

combined tips.
Taxon            
   <chr>                                    <fct>            
 1 P_macrolepidotus                         P. macrolepidotus
 2 G_orcuttii                               G. orcuttii      
 3 E_alvordensis                            alvordensis      
 4 Andys_Place                              bicolor          
 5 Big_Sage_Reservoir                       thalassinus      
 6 Bitner_Ranch                             bicolor          
 7 Camp_Cady                                mohavensis       
 8 Cottonwood_Pond_White_MT_Research_Center snyderi          
 9 Cowhead_Slough                           thalassinus      
10 Eagle_Lake                               obesus    

```{r}
s<-read.nexus("outputs/206/alt/svdq-05-nomin-boot1000.trees")
s<-consensus(s, p=0.5) # p can't be less than .5

s<-root(s, c("P_macrolepidotus"))

#ggtree(s, branch.length = 'none') %<+% block +
 # geom_tippoint(aes(shape=Species, fill=Subspecies, size=Count)) + 

tt<-ggtree(s)
tu<-tt$data %>% filter(isTip==FALSE) 
tu$label<-as.numeric(tu$label)

tlabels<-tt$data %>% filter(isTip==TRUE)  %>% select(label) %>% mutate(Taxon=label)

tlabels$Taxon<-factor(tlabels$Taxon, levels=c("P_macrolepidotus","G_orcuttii","E_alvordensis","S_thalassinus","S_bicolor",
                                              "S_newarkensis","S_isolatus","S_snyderi","S_mohavensis","S_obesus"))

ggtree(s, branch.length = "none") %<+% tlabels %>% rotate(12) %>% rotate(17)  +  
 #geom_text(data=tu, aes(x=x, y=y, label=round(label,2)*100)) +
  #geom_nodelab(aes(label=node)) +
  geom_nodelab(aes(label=label)) +
  geom_tippoint(aes(fill=Taxon, shape=Taxon), cex=4) + 
  geom_tiplab(size=4, offset = 0.5) +
  xlim(0,10) +
  scale_fill_viridis_d(option="H") +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  scale_shape_manual(values=c(22,22,23,25,25,24,24,21,21,21)) +
  theme(legend.position = "none")



ggsave("outputs/206/alt/svdq-maf05-boot1000.pdf", width=11/2, height = 8.5)
ggsave("outputs/206/alt/svdq-maf05-boot1000.jpeg", width=11/2, height = 8.5)

```